version: '3.8'

services:
  app:
    build: ./docker
    container_name: sirese_app
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./app:/var/www/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: sirese_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sirese
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
